### ISSUE TITLE
does SHACL playground or shacl-js support jsonld 1.1?

### ISSUE THREAD

**Issue by sanuann** [TopQuadrant/shacl-js#18]

**Comment by HolgerKnublauch** [comment]
JSON-LD is a serialization. SHACL-JS is an API that assumes that RDF graphs have already been loaded (in whatever format, using a 3rd party JavaScript API). So I don't see the connection.

**Comment by sanuann** [comment]
the SHACL playground has an option to write the graphs as json-ld too. It gives an error when version 1.1 json-ld is used. However, it works when written in turtle format.

**Comment by HolgerKnublauch** [comment]
If you inspect the code on SHACL playground, you can see that we use a copy of rdflib.js. You could check if that library has been updated for JSON-LD 1.1 and then use your own variation of the code.
