### ISSUE TITLE
HTTP vs. HTTPS namespace on the SHACL playground 

### ISSUE THREAD

**Issue by vcharpenay** [TopQuadrant/shacl-js#19]
It seems the examples of the [SHACL playground](https://shacl.org/playground/) use a shape graph with an HTTPS URI for the `sh:` prefix while the [W3C Rec](https://www.w3.org/TR/shacl/#conventions) mentions an HTTP URI.

I noticed that because when I am copy-pasting my own shapes, none gets registered after clicking 'Update'.

**Comment by HolgerKnublauch** [comment]
Oops, this must be a recent regression. Will look.

**Comment by HolgerKnublauch** [comment]
Has been fixed in the meantime. Thanks for the report!
