### ISSUE TITLE
Implicit target classes

### ISSUE THREAD

**Issue by RinkeHoekstra** [TopQuadrant/shacl-js#20]
The SHACL playground does not seem to understand implicit target classes, i.e. node shapes that are both an rdfs:Class and a sh:NodeShape implicitly have a reflexive sh:targetClass property.

**Comment by HolgerKnublauch** [comment]
Thanks for the pointer. This is now fixed, e.g. use

schema:Person
    a sh:NodeShape, rdfs:Class ;
    sh:property [

Could you verify and close if OK?

**Comment by RinkeHoekstra** [comment]
I verified that this works now. Thanks for fixing!
