### ISSUE TITLE
Certificate expired on https://shacl.org

### ISSUE THREAD

**Issue by umbreak** [TopQuadrant/shacl-js#29]
Your certificate created by LetsEncrypt expired the 17th of January for the website https://shacl.org

**Comment by HolgerKnublauch** [comment]
Thanks, we noticed today as well.

**Comment by umbreak** [comment]
The certificate it is expired again. I'm realizing about it because we have a CI job that verifies the links on our documentation are working correctly.

**Comment by HolgerKnublauch** [comment]
Thanks, it's fixed (again).
