### ISSUE TITLE
Create distribution that does not require rdflib

### ISSUE THREAD

**Issue by HolgerKnublauch** [TopQuadrant/shacl-js#5]
The idea of the SHACL-JS layering (as written in the W3C WG Note) is to be only tied to a minimal API, similar to the RDFJS task force's. This API can be implemented easily by RDFLib but equally easily by wrappers over Jena objects. The constraint definitions (and the rdfquery API) only use that API and are therefore, in principle, platform neutral.

Currently there is only one dist file and that includes rdflib. We need to generalize this again so that the src files can be turned into a .js file that can be included into other environments - either other .js base APIs or something completely different like a Nashorn-based implementation that uses Jena objects at runtime. Such a set-up is currently supported by the sibling SHACL API (for Java), where Jena Graphs are wrapped into JS proxies that provide a find method, as needed by the rest of the code. No rdflib is needed for that.

Looking at specific tasks, I believe the first step would be to remove the dependency from TermFactory on rdflib (make this pluggable somehow). And, if there are similar cases, decouple them too. Ideally, the bridge to rdflib is isolated to rdflib-graph.js only. Once we have this separation, the second step would be to define a second gulp target which produces a variation of dist/shacl.js that does not include rdflib and basially just bundles the other src/*.js files into a single file. Maybe let's rename the current shacl.js to shacl-rdflib.js.

**Comment by HolgerKnublauch** [comment]
BTW the main part that would need to be isolated here is rdfquery (and dependencies). This, together with dash.js, is needed at runtime by my Java-based validator. I would not need the validator itself, because I have this in Java already.

**Comment by antoniogarrote** [comment]
Hi, I have been looking at the Java code to understand a little bit better the problem. I think this is the way I'm going to try to refactor the code:

1. shacl-js will depend on rdfquery.js and dash.js files matching the ones you have now in resources/etc. The dependencies on those files are the global SHACL, $data, $shapes and TermFactory objects with the contract defined in the shacl-js draft. This should be enough to provide compatibility with the Java implementation I think. The Java validator and Jena based implementations of the Graph and TermFactory objects are already provided from your side. I will provide the equivalent ones based on the JS validator object, rdflib-graph.js and rdflib in the JS code. I will try to protect from global declarations without changing the text of rdfquery.js and dash.js

2. Shacl-js needs to properly support the shacl-js draft. Right now dash is 'hard-coded' in the project and no other extension can be registered. Support for this must be added including the loading of JS libraries correctly from URLs if they are declared in the extension that is being registered. After this, we can decide to remove completely dash from the project so it can be registered optionally as any other extension

Would this approach make sense for you?

**Comment by HolgerKnublauch** [comment]
Sounds absolutely perfect.
